### ISSUE TITLE
アルファベットの仮敵キャラをつくる

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#1]
Unity 2D shooting tutorialのスプライトを置き換える

**Comment by yanoty3d** [comment]
piskelappを使用する。oitsmalab@gmail.comでログインすると、画像が保存できるようになる。

http://www.piskelapp.com/

画面右の"Resize"機能を使って、スプライトのサイズを48px*48pxにすること。
スプライトアニメーションを作る場合は、Add new frameを使ってフレームを作っていき、最後に画面右のボタンでexportする際に export spritesheetを使ってください。ダウンロードしたＰＮＧはＵｎｉｔｙで読み込める。

**Comment by yanoty3d** [comment]
芝さんがＡ～Ｄを作成。Ｕｎｉｔｙ上にスプライトとして作成中。

**Comment by yanoty3d** [comment]
芝さんへの説明用に、テストを作りました。

https://drive.google.com/file/d/0B1IUVPG3GzFAQWNRTXZ3QzhMZWc/view?usp=sharing

**Comment by oitsmalab** [comment]
https://drive.google.com/file/d/0B1IUVPG3GzFAXzI2RkhsRGhESUE/view?usp=sharing

A~dまでのprefabを作成しました。　芝

**Comment by oitsmalab** [comment]
P~Zの試作敵キャラをPiskelで、作成しました。 柳瀬

**Comment by yanoty3d** [comment]
PQRSTUVWXYZ　ABCDは完成している。これでとりあえずゲームは作れるので、issueを閉じる。余裕があれば、追加すること

**Comment by yanoty3d** [comment]
A~Zまでのプレハブが完成。

https://drive.google.com/file/d/0B1IUVPG3GzFAODQ1R194SERJZG8/view?usp=sharing

のUnity Packageをインポートしてつかうこと。Unity5で作ったので、Unity4ではインポートできません。
