### ISSUE TITLE
自キャラを移動する

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#12]
http://blog.cshool.jp/2013/12/5215.html

に基づき、mecanimで上下左右を一定距離移動させる。

DOD
- [x] 上下左右キーを押すと対応する状態にidleから遷移し、一定時間たったらidleに戻る状態遷移がanimatorで確認できる。
- [x] 上下左右移動状態の時、決められた距離を移動する。
- [x] 各状態に割り当てられたアニメーションが表示される。

**Comment by oitsmalab** [comment]
https://drive.google.com/drive/u/0/folders/0B1IUVPG3GzFAflE1R0FROTJWdkJNVm1teWwxQkdrV1ZXVVlnWEZHdHNmYVQ4MkxodXNmQW8
に上下左右のアニメーションを追加したデータをアップロードしました。タイトルは2dAnimation.zipです。
