### ISSUE TITLE
現状のバージョンを修正して、あるアルファベットを一定数集めたら、扉が出てクリアにする

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#14]
プロジェクト名をAlphaHunterBetEasyにして、プロジェクトを今までのとは分ける。
クリア条件として、アルファベットの数を使えるようにする

**Comment by oitsmalab** [comment]
https://drive.google.com/open?id=0B1IUVPG3GzFANHVNZ1BzXzNMN2c
アルファベットの数を数えるようにしました。
