### ISSUE TITLE
終了処理

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#16]
ライフがなくなったらゲームオーバー
時間がなくなったらゲームオーバー
条件が合う時に扉にタッチしたらステージクリア

**Comment by oitsmalab** [comment]
https://drive.google.com/file/d/0B1IUVPG3GzFAcGdyLUcwTV9qdE0/view?usp=sharing

時間切れでのゲームオーバー処理を追加しました。
条件が合うときにクリア用の扉が出現する処理を追加しました。

**Comment by oitsmalab** [comment]
https://drive.google.com/open?id=0B1IUVPG3GzFAR1kyQTNUdjhvWDA

ライフがなくなったらゲームオーバーになる処理を追加しました。
条件が合う時に扉にタッチするとステージクリアになる処理を実装しました。
