### ISSUE TITLE
ボスのモーション用スプライト

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#23]
：移動するとき、傾く。
攻撃モーション、
やられアニメーション

**Comment by yanoty3d** [comment]
@d37d36a83d4516778e0d40906bee312702cfe3f4
ボスのワープ、ブレイク、移動、Burnのプレハブ
BossWarp
BossBreak
BossMove
BossBurn

**Comment by yanoty3d** [comment]
完成品はexport packageでexportして、ほかの人が使えるようにする。Google Driveの
マイドライブ/作業/AlphaHunterBetAsset/ボススプライト　に保存する。

https://drive.google.com/open?id=0B1IUVPG3GzFAa3VQN1NzQXFIdHM

**Comment by oitsmalab** [comment]
完成品をGoogleDriveに保存しました

**Comment by oitsmalab** [comment]
@fe8924ca119c9222fa501f24ce29f295c48cecd0
ボスの表情を追加しました。
・問題に正解したとき、不正解したとき
