### ISSUE TITLE
アルファベットは上から落ちてくる

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#24]
アルファベットにrigidbodyをつける、外へ出たら、消す。

**Comment by yanoty3d** [comment]
@7d7e04413cf911832c6bb3da0039662dbde8f228 では、Hashimoto_Stage を開いたがアルファベットは落ちない。Aのgravityをゼロ以上にしてもダメ。gravity.csをアタッチしてもうまくいかない。

**Comment by oitsmalab** [comment]
@fddcb0da5b3ec4d63e7cade6bc213db9b9a6cc96　に新たな変更をあげました。
スクリプトのGravityをEnemyMoveへ変更。
各アルファベットを一つにまとめ、alphabetというPrefabを作成。親のEnemyMoveの値を変更することで子の値を変更できます。
値はマイナス値で書かないと上に行きます。
OnBecameInvisibleは画面にオブジェクトが無くなったときのみ呼び出される関数ですが、unityで再生するとMainCamera外に出てもSceneViewに映っているためScene外に出ないと消えません。
