### ISSUE TITLE
敵キャラを配置する。

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#3]
決められた場所に、敵キャラを配置して表示できるようにする。

**Comment by oitsmalab** [comment]
Google DriveにC,A,T,Bのアルファベット敵キャラを配置したパッケージをアップロードしました。
https://drive.google.com/drive/folders/0B1IUVPG3GzFAfmxUTlFDYUNRVXlrNWFsZUpCRS1MeVdJVGktQ3VwLV8zallHZlhqcUJJZ2s?ltmpl=drive
ファイル名はtestalphabet.unitypackageです。
