### ISSUE TITLE
各アルファベットのスクリプト、コライダーのチェック

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#37]
AのプレハブにSpaceshipがアタッチされてますが、必要か？
各アルファベットについて、コライダーの形や大きさが適切か（特に、大きすぎないか、小さすぎないか、あたり判定が不自然でないか）

**Comment by oitsmalab** [comment]
@1d1953364d38f413f9309f4633823958423fef59 alfabet.prefabの当たり判定を確認しました。
Spaceshipの中身はExplotion関連以外の項目を削除。
Hashimoto_stage2というSceneに保存しました。
