### ISSUE TITLE
自キャラと敵キャラをあたり判定させる

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#4]
自キャラが敵キャラにあたると、敵キャラが消えて、消えた敵キャラの情報が保存される。

**Comment by oitsmalab** [comment]
Queueクラスを使って、敵アルファベットのデータを保存

**Comment by oitsmalab** [comment]
Queueクラスを使って、敵アルファベットのデータを保存

**Comment by oitsmalab** [comment]
自キャラと敵キャラの当たり判定を実装して、敵キャラが消えて、消えた敵キャラの情報が保存されるようにしたデータをGoogle Driveにアップロードしました。
https://drive.google.com/drive/folders/0B1IUVPG3GzFAfmxUTlFDYUNRVXlrNWFsZUpCRS1MeVdJVGktQ3VwLV8zallHZlhqcUJJZ2s?ltmpl=drive
ファイル名はtestalphabet_with_queueです。
使用される際は、layerなどの設定がshooting tutrialのままなので、shooting tutrial第5回のプロジェクトを開いてからパッケージをインポートしてください
