### ISSUE TITLE
アルファベットスプライトの修正

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#41]
アルファベットのスプライトの一部が見づらい（何のアルファベットかわからない）ので、見やすくする。

**Comment by oitsmalab** [comment]
@9848ad850e535b7e2546e45adfddee127ac966af
アルファベット「O,R」の修正を行いました
piskelでのアニメーション枚数を減らすことで、改善することができました

**Comment by yanoty3d** [comment]
R,Lわかりづらい、A,B,Cほそくて見づらいので、修正する。Uが角ばっているので、丸くする
