### ISSUE TITLE
シーンのクリア判定

### ISSUE THREAD

**Issue by yanoty3d** [smalab/alphahunterbet#5]
保存された「衝突済み」の敵キャラが、クリア判定にマッチしていたら、一面クリア。

**Comment by oitsmalab** [comment]
Queueクラスを使って、敵アルファベットのデータを保存

**Comment by oitsmalab** [comment]
シーンのクリア判定、特定のキーワード、CATの並びに文字を追加した後にDOORオブジェクトに触れるとクリア判定がでるようにPlayerのscriptを改変したプロジェクトファイルをGoogle Driveにalphahunterbet_clear_condition_unitypackageという名前で、アップロードしました。

https://drive.google.com/drive/folders/0B1IUVPG3GzFAfmxUTlFDYUNRVXlrNWFsZUpCRS1MeVdJVGktQ3VwLV8zallHZlhqcUJJZ2s?ltmpl=drive
利用される場合は、Layerの設定がされているため、shooting tutrial 第5回のプロジェクトを開いてから利用ください。

**Comment by oitsmalab** [comment]
CATを揃えると、クリアの判定がでる仕様に変更したパッケージをGoogle Driveにアップロードしました。
ファイル名はclear_判定です。
https://drive.google.com/drive/u/0/folders/0B1IUVPG3GzFANnFidGVUZ1haZnc?ltmpl=drive

残っている問題 : 一端クリア判定が出た後、再度CATをそろえてもドアが、出現しない
managerスクリプト内のPlayerが再度出現するときと同時に対応

クリア後はリロードを使う。
